openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/v1/categories:
    get:
      summary: Returns a list of /categories.
      description: API to retrive list of categories.
      responses:
        '200':    # status code
          description: A JSON array of category.
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Creates a category.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses: 
        '201':
          description: Created  
  /api/v1/categories/{id}:
    get:
      summary: Returns a category by ID.
      parameters:
        - id: id
          in: path
          required: true
          description: Id Category.
          schema:
            type : integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: OK
